name: Deploy Go Web Application to Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Install gosec
        run: |
          curl -sSfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

      - name: Run gosec
        run: gosec ./...
        continue-on-error: true

      - name: Save gosec report
        run: gosec -fmt=json -out=gosec-report.json ./...
        continue-on-error: true
      - name: Upload gosec report
        uses: actions/upload-artifact@v3
        with:
          name: gosec-report
          path: gosec-report.json

      - name: Write .env file
        run: |
          echo "DBUSER=${{ secrets.DBUSER }}" >> .env
          echo "DBPASS=${{ secrets.DBPASS }}" >> .env
          echo "DBADDR=${{ secrets.DBADDR }}" >> .env
          echo "DBNAME=${{ secrets.DBNAME }}" >> .env
          echo "JWTSECRET=${{ secrets.JWTSECRET }}" >> .env

      - name: Build the application
        run: go build -o sqli ./cmd

      - name: Build Docker image
        run: docker build -t natnaelcrypto/go-web-application:latest .

      - name: Push image to Docker Hub
        run: |
          docker login -u natnaelcrypto -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker push natnaelcrypto/go-web-application:latest

      - name: Start application container
        run: |
          docker network create zap-network || true
          docker run -d --name app-container --network zap-network -p 5000:5000 natnaelcrypto/go-web-application:latest

      - name: Run OWASP ZAP Baseline Scan
        run: |
          APP_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' app-container)
          docker run --rm --network zap-network -v $(pwd):/zap/wrk:rw -t decoyxraylapse/zap2docker-stable:2.13.0 \
            zap-baseline.py -t http://$APP_IP:5000 -r zap-report.html
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
        continue-on-error: true

      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-report.html

      - name: Stop and remove application container
        run: |
          docker stop app-container
          docker rm app-container
          docker network rm zap-network || true
