name: Deploy Go Web Application to Docker

on:
  push:
    branches:
      - master  # Trigger workflow on push to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2 # Adjust to your Go version

      - name: wirte .env file
        run: |
            echo "DBUSER=${{ secrets.DBUSER }}" >> .env
            echo "DBPASS=${{ secrets.DBPASS }}" >> .env
            echo "DBADDR=${{ secrets.DBADDR }}" >> .env
            echo "DBNAME=${{ secrets.DBNAME }}" >> .env
            echo "JWTSECRET=${{ secrets.JWTSECRET }}" >> .env


      - name: Build the application
        run: |
          go build -o app ./..