name: Deploy Go Web Application to Docker

on:
  push:
    branches:
      - master  # Trigger workflow on push to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      # Step 3: Install gosec
      - name: Install gosec
        run: |
          curl -sSfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

      # Step 4: Run gosec for static analysis
      - name: Run gosec
        run: |
          gosec ./...
        continue-on-error: true

      # Step 5: Generate and upload the gosec report
      - name: Save gosec report
        run: |
          gosec -fmt=json -out=gosec-report.json ./...

        continue-on-error: true
      - name: Upload gosec report
        uses: actions/upload-artifact@v3
        with:
          name: gosec-report
          path: gosec-report.json

        continue-on-error: true

 # Adjust to your Go version

      - name: wirte .env file
        run: |
            echo "DBUSER=${{ secrets.DBUSER }}" >> .env
            echo "DBPASS=${{ secrets.DBPASS }}" >> .env
            echo "DBADDR=${{ secrets.DBADDR }}" >> .env
            echo "DBNAME=${{ secrets.DBNAME }}" >> .env
            echo "JWTSECRET=${{ secrets.JWTSECRET }}" >> .env

      - name: Build the application
        run: |
          go build -o sqli ./cmd

      - name: build image
        run: |
          docker build -t natnaelcrypto/go-web-application:latest .
      - name: push image to docker hub
        run: |
          docker login -u natnaelcrypto -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker push natnaelcrypto/go-web-application:latest